version: '3.7'

services:

  app:    
    container_name: systemA-be
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        userid: $userid
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 30001
      PHP_IDE_CONFIG: serverName=Docker
    networks:
      - enterpriseX
    volumes:
      - ./:/appdata/www

  # NGINX
  web:
    container_name: systemA-web
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '7000:80'
    volumes:
      - ./:/appdata/www
    links:
      - app
    networks:
      - enterpriseX
    depends_on:
      - app

  db:
    container_name: systemA-db
    image: postgres:13-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: systemA
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: systemA-db
      TZ: 'America/La_Paz'
      PGTZ: 'America/La_Paz'

    volumes:
      - systemA-pgsql-data:/var/lib/postgresql/data
    networks:
      - enterpriseX

networks:
  enterpriseX:

volumes:
  systemA-pgsql-data:
